services:

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_DB: ngcashDB
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080